### PR TITLE
20 - Search Volume

### PR DESCRIPTION
**Pull request by arwaawan3**

### CODE REVIEW

**Comment by joshtorres** [comment]
@arwaawan3 are you able to fix the issues causing these psalm errors to fail? Plus, it looks like your composer json is out of sync with main. Can you merge main into your branch and bring it up to date.

**Review by joshtorres — CHANGES_REQUESTED** [review]
@arwaawan3 are you able to fix the issues causing these psalm errors to fail? Plus, it looks like your composer json is out of sync with main. Can you merge main into your branch and bring it up to date.

**Comment by arwaawan3** [comment]
Psalm is fine right? That checked green. I can update composer.json

**Comment by joshtorres** [comment]
Oh, right, sorry I meant the tests that are failing.

**Review by drewroberts — APPROVED** [review]
Thank you! 📚

**Pull request merged**
