### PR TITLE
Domain, explode url and save favicon #14 [TGER-129]

### PR DESCRIPTION
**Pull request by devjk1**
#14 

- add Helper method ParseUrl
- add Helper method GetFaviconUrl
- add Test for ParseUrl
- add Test for GetFaviconUrl

_errors:_

- tests cannot find both Helper methods, src/Helpers

### CODE REVIEW

**Comment by pdbreen** [comment]
For loading helper functions, combine into single PHP file - say `src/Helpers/Helpers.php` then update the `autoload` entry in composer.json with a `files` entry.  You can see an example of this in the tipoff/support:composer.json file. 
```
        "files": [
            "src/Helpers/Helpers.php"
        ]
```

**Comment by devjk1** [comment]
Tests working now, but I'm not out of the woods yet.
Psalm is complaining about vars $name and $tld not being used / referenced .. in ParseUrl.php (I think)
I initialize all vars, change them in the if block, then use all vars in return [ ].

Thanks for the help earlier Patrick

**Comment by pdbreen** [comment]
Looks like you should eliminate the initialization of `$name` and `$tld`.  Every code path results in an assignment, making the initialization value the unused value psalm is complaining about.

**Review by drewroberts — APPROVED** [review]
Thank you! ❄️

**Pull request merged**
