### PR TITLE
command to add search locales from serpapi

### PR DESCRIPTION
**Pull request by arwaawan3**
I am not sure how to get more than 10 locations from serpapi's location api. The documentation isn't very clear. 

https://serpapi.com/locations-api

### CODE REVIEW

**Comment by joshtorres** [comment]
I think the API is only if you are wanting to search for a search locale based on a string like "Austin". Since we are just taking all of those DMA locations, you should be able to use the entire locations.json file.

**Comment by arwaawan3** [comment]
@drewroberts @joshtorres Is that better? A search locale for US and then one for each of the 210 DMA regions?

**Comment by arwaawan3** [comment]
Looks like its working fine.
db result
run command

**Review by drewroberts — APPROVED** [review]
Thank you! 🙋

**Pull request merged**
