### PR TITLE
show results in ranking resource

### PR DESCRIPTION
**Pull request by arwaawan3**

### CODE REVIEW

**Comment by arwaawan3** [comment]
Screen Shot 2021-04-30 at 1 21 59 PM
Screen Shot 2021-04-30 at 1 24 26 PM
For instance ids 23, 24, 25, 26 are all subpages of the site 22. Should we only show where parent_id null, (i.e. only main result not subpages?)

**Comment by arwaawan3** [comment]
Also, it might be more helpful to actually show the domain too, the "/" isnt very clear but the domain is actually "www.stuff.tv"

**Comment by arwaawan3** [comment]
Actually, it might be ok to show the parent and child results.. otherwise we have nowhere else to see the child results. But I don't know if showing the domain would be helpful.

**Comment by joshtorres** [comment]
Yeah showing the domain would be good for sure.

**Review by joshtorres — APPROVED** [review]

**Comment by joshtorres** [comment]
Please update to fix merge conflict

**Review by joshtorres — COMMENTED** [review]
Looks good. Is this one ready?

**Comment by arwaawan3** [comment]
Yes.

**Review by joshtorres — APPROVED** [review]

**Pull request merged**
