### PR TITLE
Add factories

### PR DESCRIPTION
**Pull request by wolfrednicolas**
* PlaceDetail
* PlaceHour

### CODE REVIEW

**Review by drewroberts — APPROVED** [review]
Thank you! 🔌

**Comment by wolfrednicolas** [comment]
@pdbreen I have a question, I've seen this kind of issue in several packages, after check, I'm not able to understand what's going on...
for example

this is the issue

Caused by
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000]: General error: 1 no such table: domestic_addresses

image


Also I'm using the newest versions of the packages

image


image

**Comment by pdbreen** [comment]
Providers for package dependencies need to be added to the base TestCase `getPackageProviders` response.  In this case,  AddressesServiceProvider::class needed to be added.

https://github.com/tipoff/seo/blob/wolfrednicolas/feature/add-nova-resources/tests/TestCase.php

**Comment by wolfrednicolas** [comment]
thank you that work @pdbreen

**Comment by wolfrednicolas** [comment]
@drewroberts I think this is ready to merge, however; just one of the test is failing in the `P7.4 - L8.* - prefer-lowest - ubuntu-lates`

**Review by drewroberts — APPROVED** [review]
Thank you! 🚁

**Pull request merged**
