### PR TITLE
Add Google Search Console to check keyword search volumes

### PR DESCRIPTION
**Pull request by phuclh**
Add ability to check keyword search volumes from Google Search Console via this command:

```
php artisan keywords:check-search-volume https://tuikhoeconban.com --limit=1000
```

This will pull data from Google Search Console and check with our database. If we have that keyword in the database, then it will create or update the search volumes data in `search_volumes` table.

**Notice:** This PR requires changes from this PR (https://github.com/tipoff/laravel-google-api/pull/36) to work.

This is the video I demonstrated how it works: https://www.youtube.com/watch?v=qglfB5efRHY

### CODE REVIEW

**Comment by phuclh** [comment]
Fixes #83

**Comment by drewroberts** [comment]
> This is the video I demonstrated how it works: https://www.youtube.com/watch?v=qglfB5efRHY

THIS IS GREAT! Thank you for creating a video showing me the code in action, @phuclh!

**Comment by phuclh** [comment]
@drewroberts I still have one more question. Do we save the search volume data every range (month) or we only save the lastest range (month)?

**Comment by drewroberts** [comment]
For now, let's just save the latest range every month.

**Comment by drewroberts** [comment]
@pdbreen Could you fix the psalm errors on this PR?

**Comment by pdbreen** [comment]
@drewroberts psalm errors are fixed.  Biggest issue was composer.json allowing php 7.3 but code was using php 7.4 syntax.

**Comment by drewroberts** [comment]
Thank you, @pdbreen!

**Review by drewroberts — APPROVED** [review]
Thank you, @phuclh! 📻

**Pull request merged**
