### PR TITLE
Add string lengths

### PR DESCRIPTION
**Pull request by pdbreen**

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Just a quick note since I'm following along, I wonder about the _hit rate_ for this multi-column index. I'm not as familiar with the code, so maybe there are queries using the 6 columns or an ordered set of them, but throwing that out there as it would relate to the overall index length.

**Comment by drewroberts** [comment]
I'm not planning to use the 5 columns in a query, the main reason is to prevent the search volumes table from having multiple entries in the database for the same thing.

**Review by drewroberts — APPROVED** [review]
Thank you! 🌱

**Comment by jasonmccreary** [comment]
@drewroberts, I see, it's for uniqueness. Fair enough. ✌️

**Pull request merged**
